### ISSUE TITLE
cannot import name 'can'

### ISSUE THREAD

**Issue by brandonros** [linklayer/pyvit#41]
```
$ pip3.5 install pyvit --user
Collecting pyvit
Collecting pyserial>=3.2.1 (from pyvit)
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Installing collected packages: pyserial, pyvit
Successfully installed pyserial-3.4 pyvit-0.2.1
```

```
$ python3.5 pyvit.py
Traceback (most recent call last):
  File "pyvit.py", line 1, in <module>
    from pyvit import can
  File "/home/brandon/md1775-simulator/pyvit.py", line 1, in <module>
    from pyvit import can
ImportError: cannot import name 'can'
```

**Comment by brandonros** [comment]
Don't name your file `pyvit.py`.
